#!/usr/bin/env python3

from subprocess import PIPE, run
from time import sleep

RATIO = 1.5

while True:
    volume = run(["pactl", "get-sink-volume", "@DEFAULT_SINK@"], stdout=PIPE).stdout.decode(
        "utf-8"
    )
    volume = volume[50:-1]
    volume = int(volume[volume.index("%") - 2 : volume.index("%")])
    run(["pactl", "set-sink-volume", "@DEFAULT_SINK@", f"{int(volume * RATIO)}%", f"{volume}%"])
    sleep(1)
